### PR TITLE
Ignore `work` directory

### PR DESCRIPTION
**Pull request by jglick**

### CODE REVIEW

**Comment by jglick** [comment]
@miniOrangeDev ping

**Comment by basil** [comment]
Looks like this was fixed in jenkinsci/miniorange-saml-sp-plugin@96e1f01a94806f68ab7d77486647e14d5ad78da0.

@ashwini-xecurify @miniOrangeDev BTW see [JENKINS-69989](https://issues.jenkins.io/browse/JENKINS-69989)

**Comment by miniOrangeDev** [comment]
@basil ,

Thanks for notifying us. We will check it out.

Thanks,
miniOrange

**Comment by jglick** [comment]
Merged as 6704b55afdc9a9bbcd6ed304ba2dc8a2a7ae0105 apparently.

**Pull request closed without merging**
